function [actIcdNames ODEIcdNames] = action_bus_definition

%% Action Bus Names (From P2 Action ICD)

% See Action_Bus_Creator_Components.mdl for action types:
% These are applicable for Action Block Types only!

% The Actuator Names come from the action ICD (slightly modified for MATLAB
% compatability (no spaces, punctuation))
actIcdNames = {
    'Shoulder_FE';...       + Flexion
    'Shoulder_AbAd';...     + Adduction
    'Humeral_Rot';...       + Medial Rotation
    'Elbow';...             + Flexion
    'Wrist_Rot';...         + Supination
    'Wrist_FE';...          + Flexion
    'Wrist_Dev';...         + Ulnar Deviation
    ...
    'Index_MCP';...         + Flexion
    'Index_PIP';...         + Flexion
    'Index_DIP';...         + Flexion
    'Index_AbAd';...        + Adduction
    ...
    'Middle_MCP';...        + Flexion
    'Middle_PIP';...        + Flexion
    'Middle_DIP';...        + Flexion
    'Middle_AbAd';...       + Adduction
    ...
    'Ring_MCP';...          + Flexion
    'Ring_PIP';...          + Flexion
    'Ring_DIP';...          + Flexion
    'Ring_AbAd';...         + Adduction
    ...
    'Little_MCP';...        + Flexion
    'Little_PIP';...        + Flexion       
    'Little_DIP';...        + Flexion
    'Little_AbAd';...       + Adduction
    ...
    'Thumb_AbAd';...        + Adduction
    'Thumb_FE';...          + Flexion
    'Thumb_Rot';...         + Medial
    'Thumb_MCP';...         + Flexion
    'Thumb_IP';...          + Flexion
    ...
    'Palm_Arch';...         + Close
    };

%% ODE ICD signal order
ODEIcdNames = {...
        'Shoulder_FE';...
        'Shoulder_AbAd';...
        'Humeral_Rot';...
        'Elbow';...
        'Wrist_Rot';...
        'Wrist_Dev';... %% Note these are flipped per ODE ICD
        'Wrist_FE';...  %% Note these are flipped per ODE ICD
        ...
        'Index_AbAd';...
        'Index_MCP';...
        'Index_PIP';...
        'Index_DIP';...
        ...
        'Middle_MCP';...
        'Middle_PIP';...
        'Middle_DIP';...
        ...
        'Ring_AbAd';...
        'Ring_MCP';...
        'Ring_PIP';...
        'Ring_DIP';...
        ...
        'Little_AbAd';...
        'Little_MCP';...
        'Little_PIP';
        'Little_DIP';
        ...
        'Thumb_AbAd';...
        'Thumb_Rot';...
        'Thumb_MCP';...
        'Thumb_IP';...
        };
    
