classdef guiLimitsAdjust < Common.MiniVieObj
    properties
        hg % handle graphics
        limitData;
    end
    events
        ValueChange
    end
    methods
        function obj = guiLimitsAdjust
            obj.setupFigure();
        end
        function close(obj)
            %             obj.setLastChannels(obj.SelectedChannels)
            try
                delete(obj.hg.Figure)
            end
        end
        function setupFigure(obj)
            
            obj.hg.Figure = UiTools.create_figure('Adjust Limits');
            
            if isempty(obj.hg.Figure)
                error('Failed to create figure');
            else
                set(obj.hg.Figure,'Position',[1 1 1 1]);
            end
            
            defaultLimits = {
                'Shoulder Flexion/Extension', -45, 180;
                'Shoulder Abduction/Adduction', -180, 20;
                'Humeral Rotation', -40, 90;
                'Elbow Flexion/Extension', 0, 150;
                'Wrist Rotation', -90, 90;
                'Wrist Radial/Ulnar Deviation', -15, 45;
                'Wrist Flexion/Extension', -60, 60;
                'Finger MCP Flexion/Extension (4x)', -45, 90;
                'Finger PIP Flexion/Extension (4x)', 0, 100;
                'Finger DIP Flexion/Extension (4x)', 0, 80;
                'Index Finger Abduction/Adduction', -20, 0;
                'Ring Finger Abduction/Adduction', 0, 20;
                'Little Finger Abduction/Adduction', 0, 20;
                'Thumb CMC Abduction/Adduction', 0, 120;
                'Thumb CMC Flexion/Extension', 0, 60;
                'Thumb MCP Flexion/Extension', 0, 60;
                'Thumb IP Flexion/Extension', -15, 80;
                };
            obj.limitData = defaultLimits;
            
            set(obj.hg.Figure,'Position',pos('fig'),'CloseRequestFcn',@(src,evt)close(obj));
            
            numRows = size(defaultLimits,1);
            iRow = 1;
                % Name spans 4 (of 6) cells
                uicontrol(...
                    'Parent',obj.hg.Figure,...
                    'Style','text',...
                    'Position',pos('cntrl',1,iRow,3,1),...
                    'String','Joint Name',...
                    'Visible','on',...
                    'FontWeight','bold');
                uicontrol(...
                    'Parent',obj.hg.Figure,...
                    'Style','text',...
                    'Position',pos('cntrl',4,iRow,1,1),...
                    'String','Lower',...
                    'Visible','on',...
                    'FontWeight','bold');
                uicontrol(...
                    'Parent',obj.hg.Figure,...
                    'Style','text',...
                    'Position',pos('cntrl',5,iRow,1,1),...
                    'String','Upper',...
                    'Visible','on',...
                    'FontWeight','bold');
                uicontrol(...
                    'Parent',obj.hg.Figure,...
                    'Style','text',...
                    'Position',pos('cntrl',6,iRow,1,1),...
                    'String','Reverse',...
                    'Visible','on',...
                    'FontWeight','bold');
            for iRow = 1:numRows
                % Name spans 3 (of 6) cells
                obj.hg.LabelText(iRow) = uicontrol(...
                    'Parent',obj.hg.Figure,...
                    'Style','edit',...
                    'Position',pos('cntrl',1,iRow+1,3,1),...
                    'String',defaultLimits{iRow,1},...
                    'Callback',@(src,evt)adjustRange(obj),...
                    'Visible','on',...
                    'FontWeight','bold');
                % Lower lim in 4th column
                obj.hg.LowerLimit(iRow) = uicontrol(...
                    'Parent',obj.hg.Figure,...
                    'Style','edit',...
                    'Position',pos('cntrl',4,iRow+1,1,1),...
                    'String',num2str(defaultLimits{iRow,2}),...
                    'BackgroundColor','w',...
                    'Visible','on',...
                    'Callback',@(src,evt)adjustRange(obj),...
                    'FontWeight','bold');
                % Upper lim in 5th column
                obj.hg.UpperLimit(iRow) = uicontrol(...
                    'Parent',obj.hg.Figure,...
                    'Style','edit',...
                    'Position',pos('cntrl',5,iRow+1,1,1),...
                    'String',num2str(defaultLimits{iRow,3}),...
                    'BackgroundColor','w',...
                    'Visible','on',...
                    'Callback',@(src,evt)adjustRange(obj),...
                    'FontWeight','bold');
                obj.hg.Reverse(iRow) = uicontrol(...
                    'Parent',obj.hg.Figure,...
                    'Style','checkbox',...
                    'Position',pos('cntrl',6,iRow+1,1,1) + [40 0 0 0],...
                    'HorizontalAlignment','center',...
                    'String','',...
                    'Visible','on',...
                    'Callback',@(src,evt)adjustRange(obj),...
                    'FontWeight','bold');
            end
        end
        function adjustRange(obj)
            % read input and verify
            
            cellLowerLim = get(obj.hg.LowerLimit,'String');
            lowerLim = cellfun(@str2double,cellLowerLim);
            
            if any(isnan(lowerLim))
                % restore previous
                set(obj.hg.LowerLimit,{'String'},obj.limitData(:,2));
            end
            
            cellUpperLim = get(obj.hg.UpperLimit,'String');
            upperLim = cellfun(@str2double,cellUpperLim);
            
            if any(isnan(upperLim))
                % restore previous
                set(obj.hg.UpperLimit,{'String'},obj.limitData(:,3));
            end

            % always restore labels
            set(obj.hg.LabelText,{'String'},obj.limitData(:,1));
            
            notify(obj,'ValueChange');

        end
    end
end

function p = pos( action, varargin )
% src: comp.soft-sys.matlab "Creating a GUI without using GUIDE"
% pos is called by the function VisualStuff. A construct
% like this makes it "easy" to adjust the sizes of the
% controls.
% In this subroutine I made a mess of [x,y]-coordinates
% and rows and columns. That hole I will fall into.

p = zeros( 1, 4 ) - 999;

nCol = 6;
nRow = 18;
CntrlHeight = 30;
CntrlWidth = 100;
CntrlGap = 0;
CntrlMarg = 6;

FigHeight = nRow * CntrlHeight ...
    + (nRow-1)*CntrlGap ...
    + 2*CntrlMarg ;

switch lower( action )
    case {'fig'},
        FigWidth = nCol * CntrlWidth ...
            + (nCol-1)*CntrlGap ...
            + 2*CntrlMarg ;
        p = [ 50, 150, FigWidth, FigHeight ];
        
    case {'cntrl'},
        if ( nargin == 5 ),
            [iC,iR,iW,iH] = deal( varargin{:} );
        else
            error( 'pos: Should not occur' ),
        end,
        
        p(1) = CntrlMarg + (iC-1)*(CntrlWidth+CntrlGap);
        p(2) = FigHeight - CntrlMarg ...
            - iR*CntrlHeight - (iR-1)*CntrlGap;
        p(3) = iW*CntrlWidth + (iW-1)*CntrlGap;
        p(4) = iH*CntrlHeight + (iH-1)*CntrlGap;
        
    otherwise
        error( 'pos: Should not occur' ),
end %switch
end %pos
%/ ---------------------
