# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='spikes.proto',
  package='',
  serialized_pb='\n\x0cspikes.proto\"K\n\tSpike_msg\x12\n\n\x02ts\x18\x01 \x02(\x04\x12\x0c\n\x04\x63han\x18\x02 \x02(\r\x12\x0c\n\x04unit\x18\x03 \x01(\r\x12\t\n\x01w\x18\x06 \x01(\x0c\x12\x0b\n\x03seq\x18\x07 \x01(\r\"\xcf\x01\n\x0b\x44isplay_msg\x12\x0e\n\x06\x63ursor\x18\x01 \x03(\x01\x12\x0e\n\x06target\x18\x02 \x03(\x01\x12\r\n\x05touch\x18\x03 \x01(\x08\x12\x0e\n\x06juicer\x18\x04 \x01(\x08\x12\x0e\n\x06manual\x18\x05 \x01(\x08\x12\x12\n\ncursorSize\x18\x06 \x01(\x02\x12\x12\n\ntargetSize\x18\x07 \x01(\x02\x12\x13\n\x0b\x63ursorAlpha\x18\x08 \x01(\x02\x12\x13\n\x0btargetAlpha\x18\t \x01(\x02\x12\x0e\n\x06irDiff\x18\n \x01(\x02\x12\x0f\n\x07\x62gColor\x18\x0b \x03(\x02')




_SPIKE_MSG = descriptor.Descriptor(
  name='Spike_msg',
  full_name='Spike_msg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='ts', full_name='Spike_msg.ts', index=0,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='chan', full_name='Spike_msg.chan', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='unit', full_name='Spike_msg.unit', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='w', full_name='Spike_msg.w', index=3,
      number=6, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='seq', full_name='Spike_msg.seq', index=4,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=16,
  serialized_end=91,
)


_DISPLAY_MSG = descriptor.Descriptor(
  name='Display_msg',
  full_name='Display_msg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='cursor', full_name='Display_msg.cursor', index=0,
      number=1, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='target', full_name='Display_msg.target', index=1,
      number=2, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='touch', full_name='Display_msg.touch', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='juicer', full_name='Display_msg.juicer', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='manual', full_name='Display_msg.manual', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='cursorSize', full_name='Display_msg.cursorSize', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='targetSize', full_name='Display_msg.targetSize', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='cursorAlpha', full_name='Display_msg.cursorAlpha', index=7,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='targetAlpha', full_name='Display_msg.targetAlpha', index=8,
      number=9, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='irDiff', full_name='Display_msg.irDiff', index=9,
      number=10, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='bgColor', full_name='Display_msg.bgColor', index=10,
      number=11, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=94,
  serialized_end=301,
)

DESCRIPTOR.message_types_by_name['Spike_msg'] = _SPIKE_MSG
DESCRIPTOR.message_types_by_name['Display_msg'] = _DISPLAY_MSG

class Spike_msg(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SPIKE_MSG
  
  # @@protoc_insertion_point(class_scope:Spike_msg)

class Display_msg(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DISPLAY_MSG
  
  # @@protoc_insertion_point(class_scope:Display_msg)

# @@protoc_insertion_point(module_scope)
